config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'twitch/login'
  post 'twitch/sign_user'
  if ENV['RAILS_ENV'] == 'development'
    devise_for :viewers
  else
    devise_for :viewers, skip: %i[registration recoverable confirmable]
  end
  devise_for :admins

  resources :tracks, only: %i[index] do
    resources :likes, only: %i[create]
    delete 'like', as: :like, to: 'likes#destroy'
  end

  patch '/tracks/:id', to: 'tracks#review', as: 'track_review'

  resources :streams do
    resources :tracks, only: %i[index new create]
    resources :samples, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample < ApplicationRecord
  LINK_REGEX = %r{\A(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:/[^\s]*)?\z}i.freeze

  belongs_to :stream

  validates :name, presence: true
  validates :link, presence: true, format: { with: LINK_REGEX }
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_stream
  after_action :verify_authorized

  def destroy
    @sample = Sample.find(params[:id])
    authorize @sample
    @destroyed = @sample.destroy
  end

  def create
    @sample = Sample.new(sample_params)
    authorize @sample
    @saved = @sample.save
  end

  private

  def sample_params
    params.require(:sample).permit(:name, :link, :stream_id)
  end

  def set_stream
    @stream = Stream.find(params[:stream_id])
  end

end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.haml
= form_with(model: [stream, sample], remote: true) do |form|
  - if sample.errors.any?
    #error_explanation.notification.is-danger.is-small
      %a.delete
      %ul
        - sample.errors.full_messages.each do |message|
          %li
            = message
  .columns
    .column
      .field
        = form.text_field :name, class: 'input is-small', placeholder: :name
    .column
      .field
        = form.text_field :link, class: 'input is-small', placeholder: :link
        = form.hidden_field :stream_id, value: stream.id
    .column.is-1
      = form.submit 'Save', class: 'is-primary acid-green-button button is-small is-fullwidth'
  

app/views/samples/_sample.html.haml
%tr{id: dom_id(sample)}
  %td
    = link_to sample.link, target: '_blank' do
      %i.fas.fa-file-audio.has-text-black
  %td.has-text-left
    = sample.name
  - if admin_signed_in?
    %td.has-text-right
      = link_to stream_sample_path(sample.stream_id, sample), remote: true, method: :delete do
        %i.fas.fa-trash-alt.has-text-danger

app/views/samples/create.js.erb
<% if @saved %>
$("#<%= dom_id(@stream) %> .samples").append('<%= j render @sample %>')
$("#<%= dom_id(@stream) %> .samples-form").html("<%= j render 'form', stream: @stream, sample: Sample.new %>")
<% else %>
$("#<%= dom_id(@stream) %> .samples-form").html("<%= j render 'form', stream: @stream, sample: @sample %>")
// Delete notification on close button
$('.notification .delete').on('click', (event) => {
  event.preventDefault()
  $('#error_explanation').remove()
})
<% end %>

app/views/samples/destroy.js.erb
<% if @destroyed %>
$("#<%= dom_id(@sample) %>").remove()
<% end %>