config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'twitch/login'
  post 'twitch/sign_user'
  if ENV['RAILS_ENV'] == 'development'
    devise_for :viewers
  else
    devise_for :viewers, skip: %i[registration recoverable confirmable]
  end
  devise_for :admins

  resources :tracks, only: %i[index] do
    resources :likes, only: %i[create]
    delete 'like', as: :like, to: 'likes#destroy'
  end

  patch '/tracks/:id', to: 'tracks#review', as: 'track_review'

  resources :streams do
    resources :tracks, only: %i[index new create]
    resources :samples, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/track.rb
class Track < ApplicationRecord
  SOUND_CLOUD_REGEX = /\Ahttps?:\/\/[soundcloud.com]+\/[\w]+\/[\w]/

  belongs_to :viewer
  belongs_to :stream
  has_many :likes, dependent: :destroy

  validates :soundcloud_url, presence: true, format: { with: SOUND_CLOUD_REGEX }

  def create_likes(viewer, new_like_attributes)
    likes_amount = viewer.subscriber? ? 3 : 1
    likes_amount.times { Like.create new_like_attributes }
    reload
  end

  def destroy_likes_from(viewer)
    likes.where(viewer_id: viewer.id).destroy_all
    reload
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  include Pagy::Backend
  Pagy::DEFAULT[:items] = 10

  before_action :authenticate_viewer!, except: %i[index show review]
  before_action :set_stream, except: %i[index show review]
  before_action :authenticate_admin!, only: :review
  before_action :set_track, only: :review
  after_action :verify_authorized, except: :review

  def index
    @tracks = Track.all.includes(:viewer).order('tracks.likes_count desc')
    authorize @tracks
    reorder_tracks if admin_signed_in?
    @current_viewer_liked_tracks = viewer_signed_in? ? current_viewer.liked_tracks.ids : []
    @pagy, @tracks = pagy(@tracks)
  end

  def new
    @track = @stream.tracks.build
    authorize @track
  end

  def create
    @track = Track.new(track_params)
    authorize @track
    @track.viewer = current_viewer
    respond_to do |format|
      if @track.save
        format.html { redirect_to @track.stream, notice: "Track was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def review
    @track.update(reviewed: !@track.reviewed)
    respond_to do |format|
      format.js
    end
  end

  private

  def reorder_tracks
    @tracks = @tracks.reorder('likes_count desc')
    @tracks = @tracks.order('viewers.subscriber desc, tracks.created_at desc') if admin_signed_in?
  end

  def set_stream
    @stream = Stream.find(params[:stream_id])
  end

  def track_params
    params.require(:track).permit(:soundcloud_url, :stream_id, :viewer_id)
  end

  def set_track
    @track = Track.find(params[:id])
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
  include Pagy::Frontend
end

app/views/tracks/_form.html.haml
= form_with(model: [stream, track], local: true) do |form|
  - if track.errors.any?
    #error_explanation.notification.is-danger
      %button.delete
      %h3.title.is-3
        = pluralize(track.errors.count, "error")
        prohibited this track from being saved:
      %ul
        - track.errors.full_messages.each do |message|
          %li.is-4
            = message
  .field
    = form.label :soundcloud_url, class: 'label'
    = form.text_field :soundcloud_url, class: 'input'
    = form.hidden_field :stream_id
    = form.hidden_field :viewer_id
  .actions
    = form.submit 'Save', class: 'button acid-green-button is-primary'

app/views/tracks/_reviewed.html.haml
.level-left
  - url = track_review_path(track)
  - method = :patch
  - color = reviewed

  = link_to url, method: method, remote: true, class: "level-item #{ reviewed ? '' : 'has-text-danger'}" do
    %span.icon.is-small
      %i.fas.fa-check-circle
    &nbsp;
    

app/views/tracks/_track.html.haml
%article.track.media{id: dom_id(track)}
  %figure.media-left
    %p.image.is-64x64
      %img{:src => track.viewer.profile_image_url}/
  .media-content
    .content
      %h4
        = link_to twitch_account_link(track.viewer.twitch_login), target: :blank, class: 'has-text-black' do
          %strong.has-text-light
            = track.viewer.twitch_display_name
          - if track.viewer.subscriber?
            &nbsp;
            %i.fas.fa-star.acid-green
      = link_to 'url', track.soundcloud_url, class: 'soundcloud-url'
    %nav.level.is-mobile
      .likes
        = render 'likes/like', track: track, liked: @current_viewer_liked_tracks.include?(track.id)
      - if current_admin 
        .review
          = render 'tracks/reviewed', track: track, reviewed: track.reviewed

app/views/tracks/index.html.haml
%h1.title.is-1.has-text-light Tracks

.columns
  .column.is-three-fifths
    .subtitle.is-6 
      %h6.has-text-light
        Warning, valume may be too high
        %i.fa.fa-volume-up

.tracks
  = render @tracks
%br/
.tracks-pagination
  = pagy_bulma_nav(@pagy).html_safe

app/views/tracks/index.js.erb
$('.tracks').html("<%= j render @tracks %>")
$('.tracks-pagination').html("<%= j pagy_bulma_nav(@pagy).html_safe %>")
displaySoundCloudTracks()

// Find a way to export these functions from the js files

function displaySoundCloudTracks() {
  if ($('.track').length > 0) {
    $('.track').each((index, element) => {
      const urlElement = $($(element).find('.soundcloud-url'))
      const urlPath = urlElement.attr('href')
      displaySoundCloudTrack(urlElement, urlPath)
    }) 
  }
}

function displaySoundCloudTrack(urlElement, urlPath) {
  const settings = {
    "async": true,
    "crossDomain": true,
    "url": "https://soundcloud.com/oembed",
    "method": "POST",
    "headers": {},
    "data": {
      "format": "json",
      "url": urlPath,
      "maxheight": "166"
    }, success: (data) => {
      urlElement.html(data.html)
    }
  }
  
  $.ajax(settings)
}

app/views/tracks/new.html.haml
%h1.title.is-1.has-text-light New track
= render 'form', track: @track, stream: @stream

app/views/tracks/review.js.erb
$("#<%= dom_id @track %> .review").html("<%= j render 'tracks/reviewed', track: @track, reviewed: @track.reviewed %>")