config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'twitch/login'
  post 'twitch/sign_user'
  if ENV['RAILS_ENV'] == 'development'
    devise_for :viewers
  else
    devise_for :viewers, skip: %i[registration recoverable confirmable]
  end
  devise_for :admins

  resources :tracks, only: %i[index] do
    resources :likes, only: %i[create]
    delete 'like', as: :like, to: 'likes#destroy'
  end

  patch '/tracks/:id', to: 'tracks#review', as: 'track_review'

  resources :streams do
    resources :tracks, only: %i[index new create]
    resources :samples, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stream.rb
class Stream < ApplicationRecord
  has_many :tracks, dependent: :destroy
  has_many :samples, dependent: :destroy
  belongs_to :admin
  validates :title, presence: true
end

app/controllers/streams_controller.rb
# frozen_string_literal: true

class StreamsController < ApplicationController
  include Pagy::Backend
  Pagy::DEFAULT[:items] = 8

  before_action :set_stream, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: %i[index show]

  # GET /streams or /streams.json
  def index
    @streams = Stream.all.order(:created_at).includes(:samples)
    authorize @streams
    @pagy, @streams = pagy(@streams)
  end

  # GET /streams/1 or /streams/1.json
  def show
    authorize @stream
    @new_stream_track = @stream.tracks.build
    @tracks = @stream.tracks.order('likes_count desc').includes(:viewer)
    @tracks = @tracks.where(reviewed: true) unless admin_signed_in?
    reorder_tracks if admin_signed_in?
    @current_viewer_liked_tracks = viewer_signed_in? ? current_viewer.liked_tracks.ids : []
    @pagy, @tracks = pagy(@tracks)
  end

  # GET /streams/new
  def new
    @stream = Stream.new
    authorize @stream
  end

  # GET /streams/1/edit
  def edit
    authorize @stream
  end

  # POST /streams or /streams.json
  def create
    @stream = Stream.new(stream_params)
    @stream.admin = current_admin
    authorize @stream
    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: "Stream was successfully created." }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1 or /streams/1.json
  def update
    authorize @stream
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to @stream, notice: "Stream was successfully updated." }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1 or /streams/1.json
  def destroy
    authorize @stream
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to streams_url, notice: "Stream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def reorder_tracks
    @tracks = @tracks.reorder('likes_count desc')
    @tracks = @tracks.reorder('viewers.subscriber desc, tracks.created_at asc') if admin_signed_in?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_stream
    @stream = Stream.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def stream_params
    params.require(:stream).permit(:title, :aired_at, :receiving_tracks)
  end

end

app/views/streams/_form.html.haml
= form_with(model: stream, local: true) do |form|
  - if stream.errors.any?
    .notification.is-danger#error_explanation
      %button.delete
      %h2
        = pluralize(stream.errors.count, "error")
        prohibited this stream from being saved:
      %ul
        - stream.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title, class: 'label'
    = form.text_field :title, class: 'input'
  .field
    = form.label :aired_at, class: 'label'
    = form.datetime_field :aired_at
  .field
    = form.label :receiving_tracks, class: 'checkbox' do
      %strong.has-text-light Receiving tracks
      = form.check_box :receiving_tracks, class: 'checkbox'
  .actions
    = form.submit 'Save', {class: 'is-primary acid-green-button button'}

app/views/streams/_samples.html.haml
%table.table.is-hoverable.samples.is-striped
  %tbody
    = render stream.samples

app/views/streams/_stream.html.haml
.stream-card{id: dom_id(stream)}
  = link_to stream do
    = image_tag("default_stream_image.jpg", class: 'stream-image')
    .stream-date
      = stream.aired_at.strftime('%d/%m - %H:%M')
    .stream-title
      = stream.title
    .stream-tracks
      = button_to stream_path(stream), { method: 'get', class: 'btn stream-track-button' } do 
        Ir a Stream
        %i.fa.fa-solid.fa-caret-right.pl-2
        
        
        

app/views/streams/edit.html.haml
%h1 Editing Stream
= render 'form', stream: @stream
= link_to 'Show', @stream
|
= link_to 'Back', streams_path

app/views/streams/index.html.haml
.column.is-6-desktop.is-offset-3-desktop
  = render 'shared/top_m_beats'
  .stream-cards
    = render @streams.reorder(aired_at: :desc)
    - if @streams.size % 3 != 0
      - (3 - @streams.size % 3).times do
        .stream-card.empty-card
  .pt-5
    = pagy_bulma_nav(@pagy).html_safe
 

app/views/streams/new.html.haml
%h1.title.has-text-light New Stream
.stream-card
  .card-content
    = render 'form', stream: @stream
%br/
= link_to 'Back', streams_path

app/views/streams/show.html.haml
.column.is-6-desktop.is-offset-3-desktop
  = render 'shared/top_m_beats'
  .columns.stream-information
    .column.is-4
      = image_tag("default_stream_image.jpg", class: 'stream-image')
    .column.is-4
      .stream-date
        = @stream.aired_at.strftime('%d/%m - %H:%M')
      .stream-title
        = @stream.title
      .stream-description
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    .column.is-4.is-flex.is-flex-direction-column.is-justify-content-space-between
      .is-flex.is-justify-content-right
        - if @stream.receiving_tracks
          .aired-label
            %i.fa.fa-circle
            EN VIVO
      - if current_admin
        .is-flex.is-justify-content-end
          = button_to edit_stream_path(@stream), { method: 'get', class: 'btn edit-button' } do 
            Editar
          = button_to stream_path(@stream), { method: 'delete', class: 'btn delete-button', data: { confirm: 'Are you sure?' } } do 
            Eliminar
  %hr
    .content
      %h4.is-4.has-text-white Samples
      - if current_admin
        .content.samples-form
          = render 'samples/form', sample: Sample.new, stream: @stream
      = render 'samples', stream: @stream
  %br
  .columns
    .column.is-three-fifths
      - if policy(@new_stream_track).new?
        = link_to new_stream_track_path(@stream), class: 'button' do
          %strong
            Submit track &nbsp;
          %i.fab.fa-soundcloud.fa-2x.soundcloud-orange
      .content.is-small
        %p.has-text-light
          Warning, valume may be too high
          %i.fa.fa-volume-up
  .tracks
    = render @tracks
  %br/
  .tracks-pagination
    = pagy_bulma_nav(@pagy).html_safe