config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'twitch/login'
  post 'twitch/sign_user'
  if ENV['RAILS_ENV'] == 'development'
    devise_for :viewers
  else
    devise_for :viewers, skip: %i[registration recoverable confirmable]
  end
  devise_for :admins

  resources :tracks, only: %i[index] do
    resources :likes, only: %i[create]
    delete 'like', as: :like, to: 'likes#destroy'
  end

  patch '/tracks/:id', to: 'tracks#review', as: 'track_review'

  resources :streams do
    resources :tracks, only: %i[index new create]
    resources :samples, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |_type, msg|
  .notification.is-warning
    %button.delete
    = msg

app/views/layouts/_navbar.html.haml
%nav.navbar.is-black{"aria-label" => "main navigation", :role => "navigation"}
  .navbar-brand
    %a.navbar-item{:href => "https://www.twitch.tv/foreroplays"}
      %img{:height => "38", :src => "https://static-cdn.jtvnw.net/jtv_user_pictures/fc675b30-68ce-4ce5-8191-283a07a5be5c-profile_image-70x70.png", :width => "28"}/
    %a.navbar-burger{"aria-expanded" => "false", "aria-label" => "menu", "data-target" => "navbarBasicExample", :role => "button"}
      %span{"aria-hidden" => "true"}
      %span{"aria-hidden" => "true"}
      %span{"aria-hidden" => "true"}
  #navbarBasicExample.navbar-menu
    .navbar-start
      = link_to root_path, class: 'navbar-item' do
        %strong.acid-green
          Inicio
      = link_to streams_path, class: 'navbar-item' do
        %strong.acid-green
          Streams
    .navbar-end
      .navbar-item
        - if viewer_signed_in?
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link
              = current_viewer.twitch_display_name
            .navbar-dropdown
              = link_to destroy_viewer_session_path, method: :delete, class: 'navbar-item' do
                Sign out
        - elsif !current_admin
          .buttons
            %a.button.is-light{href: twitch_login_url}
              %i.fab.fa-twitch.is-dark.fa-lg
              &nbsp; Log in
        - if admin_signed_in?
          .navbar-item.has-dropdown.is-hoverable
            %a.navbar-link.has-text-light
              %i.fas.fa-user-shield
              &nbsp; Admin
            .navbar-dropdown
              = link_to 'New stream', new_stream_path, class: 'navbar-item has-text-light'
              = link_to destroy_admin_session_path, method: :delete, class: 'navbar-item has-text-light' do
                Sign out
                

app/views/layouts/application.html.haml
%html
  %head
    %title BeatsByForero
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://static-cdn.jtvnw.net/jtv_user_pictures/fc675b30-68ce-4ce5-8191-283a07a5be5c-profile_image-70x70.png", :rel => "shortcut icon"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open Sans", :rel => "stylesheet"}/
  %body
    = render 'layouts/navbar'
    = render 'layouts/flash_messages'
    .section.m-0.p-0
      .container.m-0.p-0
        = yield